version: '3.5'
services:
  app:
    image: ${TEST_IMAGE_NAME:-jimsihk/alpine-php-nginx:local}
    build: .
  sut:
    image: alpine:20220715
    depends_on:
      - app
    command: /tmp/run_tests.sh
    volumes:
      - "./run_tests.sh:/tmp/run_tests.sh:ro"
