name: Update DockerHub Description

on:
  push:
    branches: ["dev"]
    paths:
      - README.md
      - .github/workflows/update-dockerhub-desc.yml

jobs:
  update-dockerhub-desc:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v5

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          short-description: ${{ github.event.repository.description }}